version: "3"
services:
  gazi:
    build: .
    container_name: gazi
    image: andreasarne/gazi:build
    volumes:
      - ./courses:/home/dbwebb/courses
      - /home/zeldah/.ssh:/home/dbwebb/.ssh-keys
      - /home/zeldah/.dbwebb.config:/home/dbwebb/.dbwebb.config.real
    environment:
      - "VIEWER_PORT=8083"
    ports:
      - "8083:8083"
