version: "3"
services:
  gazi:
    build: .
    container_name: gazi
    image: andreasarne/gazi:build
    volumes:
      - ./courses:/home/dbwebb/courses
      - /home/aar/.ssh:/home/dbwebb/.ssh-keys
      - /home/aar/.dbwebb.config:/home/dbwebb/.dbwebb.config.real
    ports:
      - "8083:8083"
